version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  finance-helper-postgres:
    image: postgres
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'pass'
    ports:
      - '5432:5432'
    networks:
      - app-network

  finance-helper-test-postgres:
    image: postgres
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'pass'
    ports:
      - '5433:5432'
    networks:
      - app-network
